In [2]:
import pandas as pd
import numpy as np

In [3]:
ruta_bank =r"C:\Users\laura\OneDrive\Escritorio\bank-additional.csv"
df_bank = pd.read_csv(ruta_bank, sep=',', header = 'infer', index_col = None)

In [4]:
df_bank.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [5]:
df_bank.shape

(43000, 24)

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
pd.set_option('display.max_rows', None)

In [8]:
pd.set_option('display.max_rows', None)

In [9]:
df_bank.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [10]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB

In [11]:
df_bank.describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [12]:
# elimino las filas 'housing' y 'loan' porque esas columnas no afectará al análisis.
df_bank = df_bank.drop(['housing', 'loan'], axis=1)

In [13]:
# ahora voy a sustituir la edad por la mediana
mediana_edad = df_bank['age'].median()
df_bank['age'] = df_bank['age'].fillna(mediana_edad)

In [14]:
# sigo con las columnas de texto, sustituyo los valores nulos por 'unknown'
columnas_texto = ['job', 'marital', 'education']
for col in columnas_texto:
    df_bank[col] = df_bank[col].fillna('unknown')

In [15]:
# la columna 'default' tiene muchos valores nulos, voy a sustituirlos por 'unknown'
df_bank['default'] = df_bank['default'].fillna('unknown')

In [16]:
# por último, voy a eliminar la columna 'unnamed:0' porque podría ser un duplicado del índice
if 'Unnamed: 0' in df_bank.columns:
    df_bank = df_bank.drop(columns=['Unnamed: 0'])

In [17]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             43000 non-null  float64
 1   job             43000 non-null  str
 2   marital         43000 non-null  str
 3   education       43000 non-null  str
 4   default         43000 non-null  object
 5   contact         43000 non-null  str
 6   duration        43000 non-null  int64
 7   campaign        43000 non-null  int64
 8   pdays           43000 non-null  int64
 9   previous        43000 non-null  int64
 10  poutcome        43000 non-null  str
 11  emp.var.rate    43000 non-null  float64
 12  cons.price.idx  42529 non-null  str
 13  cons.conf.idx   43000 non-null  str
 14  euribor3m       33744 non-null  str
 15  nr.employed     43000 non-null  str
 16  y               43000 non-null  str
 17  date            42752 non-null  str
 18  latitude        43000 non-null  float64
 19  longitude       43000 non-null  float64
 20  id_             43000 non-null  str
dtypes: float64(4), int64(4), object(1), str(12)
memory usage: 6.9+ MB

In [18]:
#voy a convertir a numéricas 'cons.price,idx' y 'euribor3m' porque son valores numéricos pero están como texto
df_bank['cons.price.idx'] = pd.to_numeric(df_bank['cons.price.idx'], errors='coerce')
df_bank['euribor3m'] = pd.to_numeric(df_bank['euribor3m'], errors='coerce')
#errors = 'coerce' convertirá los valores no numéricos en NaN.

In [19]:
#ahora voy a sustituir los valores nulos con la mediana de cada columna
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].fillna(df_bank['cons.price.idx'].median())
df_bank['euribor3m'] = df_bank['euribor3m'].fillna(df_bank['euribor3m'].median())

In [20]:
#la columna 'date' la voy a convertir a tipo fecha 
df_bank['date'] = pd.to_datetime(df_bank['date'], errors='coerce')

if not df_bank['date'].dropna().empty:
    fecha_moda = df_bank['date'].mode().values[0]
else:
    fecha_moda = df_bank['date'].min()
    
df_bank['date'] = df_bank['date'].fillna(fecha_moda)

C:\Users\laura\AppData\Local\Temp\ipykernel_956\3316836956.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_bank['date'] = pd.to_datetime(df_bank['date'], errors='coerce')

In [21]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             43000 non-null  float64
 1   job             43000 non-null  str
 2   marital         43000 non-null  str
 3   education       43000 non-null  str
 4   default         43000 non-null  object
 5   contact         43000 non-null  str
 6   duration        43000 non-null  int64
 7   campaign        43000 non-null  int64
 8   pdays           43000 non-null  int64
 9   previous        43000 non-null  int64
 10  poutcome        43000 non-null  str
 11  emp.var.rate    43000 non-null  float64
 12  cons.price.idx  0 non-null      float64
 13  cons.conf.idx   43000 non-null  str
 14  euribor3m       43000 non-null  float64
 15  nr.employed     43000 non-null  str
 16  y               43000 non-null  str
 17  date            0 non-null      datetime64[s]
 18  latitude        43000 non-null  float64
 19  longitude       43000 non-null  float64
 20  id_             43000 non-null  str
dtypes: datetime64[s](1), float64(6), int64(4), object(1), str(9)
memory usage: 6.9+ MB

In [22]:
#voy a ver si hay valores duplicados en el DataFrame y eliminarlos si es necesario
duplicados = df_bank.duplicated().sum()
print(f"Tienes {duplicados} filas duplicadas.")

Tienes 0 filas duplicadas.

In [23]:
#voy a comprobar si hay algun ID de clientes repetidos
ids_duplicados = df_bank['id_'].duplicated().sum()
print(f"Tienes {ids_duplicados} IDs de clientes duplicados.")

Tienes 0 IDs de clientes duplicados.

In [24]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             43000 non-null  float64
 1   job             43000 non-null  str
 2   marital         43000 non-null  str
 3   education       43000 non-null  str
 4   default         43000 non-null  object
 5   contact         43000 non-null  str
 6   duration        43000 non-null  int64
 7   campaign        43000 non-null  int64
 8   pdays           43000 non-null  int64
 9   previous        43000 non-null  int64
 10  poutcome        43000 non-null  str
 11  emp.var.rate    43000 non-null  float64
 12  cons.price.idx  0 non-null      float64
 13  cons.conf.idx   43000 non-null  str
 14  euribor3m       43000 non-null  float64
 15  nr.employed     43000 non-null  str
 16  y               43000 non-null  str
 17  date            0 non-null      datetime64[s]
 18  latitude        43000 non-null  float64
 19  longitude       43000 non-null  float64
 20  id_             43000 non-null  str
dtypes: datetime64[s](1), float64(6), int64(4), object(1), str(9)
memory usage: 6.9+ MB

In [25]:
#voy a arreglar las columnas que se han quedado en 0 non-null
df_bank['date'] = pd.to_datetime(df_bank['date'], errors='coerce', dayfirst=True)

for col in ['cons.price.idx', 'euribor3m']:
    if df_bank[col].dtype == 'object':
        df_bank[col] = df_bank[col].str.replace(',', '.', regex=False)
    df_bank[col] = pd.to_numeric(df_bank[col], errors='coerce')
    df_bank[col] = df_bank[col].fillna(df_bank[col].median())

In [26]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             43000 non-null  float64
 1   job             43000 non-null  str
 2   marital         43000 non-null  str
 3   education       43000 non-null  str
 4   default         43000 non-null  object
 5   contact         43000 non-null  str
 6   duration        43000 non-null  int64
 7   campaign        43000 non-null  int64
 8   pdays           43000 non-null  int64
 9   previous        43000 non-null  int64
 10  poutcome        43000 non-null  str
 11  emp.var.rate    43000 non-null  float64
 12  cons.price.idx  0 non-null      float64
 13  cons.conf.idx   43000 non-null  str
 14  euribor3m       43000 non-null  float64
 15  nr.employed     43000 non-null  str
 16  y               43000 non-null  str
 17  date            0 non-null      datetime64[s]
 18  latitude        43000 non-null  float64
 19  longitude       43000 non-null  float64
 20  id_             43000 non-null  str
dtypes: datetime64[s](1), float64(6), int64(4), object(1), str(9)
memory usage: 6.9+ MB

In [27]:
#vuelvo a corregir los valores 0 non-null en la columna 'cons.price.idx'
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].astype(str)

#voy a quitar espacios, cambiar comas por puntos y eliminar cualquier cosa que no sea número o punto
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].str.strip()
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].str.replace(',', '.', regex=False)
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].str.replace(r'[^\d.]', '', regex=True)

#convertir a número flotante
df_bank['cons.price.idx'] = pd.to_numeric(df_bank['cons.price.idx'], errors='coerce')

#por último, voy a sustituir los valores nulos con la mediana de la columna
mediana_cons = df_bank['cons.price.idx'].median()
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].fillna(mediana_cons)

In [28]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             43000 non-null  float64
 1   job             43000 non-null  str
 2   marital         43000 non-null  str
 3   education       43000 non-null  str
 4   default         43000 non-null  object
 5   contact         43000 non-null  str
 6   duration        43000 non-null  int64
 7   campaign        43000 non-null  int64
 8   pdays           43000 non-null  int64
 9   previous        43000 non-null  int64
 10  poutcome        43000 non-null  str
 11  emp.var.rate    43000 non-null  float64
 12  cons.price.idx  0 non-null      float64
 13  cons.conf.idx   43000 non-null  str
 14  euribor3m       43000 non-null  float64
 15  nr.employed     43000 non-null  str
 16  y               43000 non-null  str
 17  date            0 non-null      datetime64[s]
 18  latitude        43000 non-null  float64
 19  longitude       43000 non-null  float64
 20  id_             43000 non-null  str
dtypes: datetime64[s](1), float64(6), int64(4), object(1), str(9)
memory usage: 6.9+ MB

In [29]:
# voy a ordenar todo lo anterior para que quede más limpio y legible
import pandas as pd
import numpy as np

In [30]:
ruta_bank =r"C:\Users\laura\OneDrive\Escritorio\bank-additional.csv"
df_bank = pd.read_csv(ruta_bank, sep=',', header = 'infer', index_col = None)

In [31]:
# 1. Eliminar filas con nulos en housing y loan (que son poquitas)
df_bank = df_bank.dropna(subset=['housing', 'loan'])

# 2. Rellenar la edad con la mediana y pasarla a entero (int)
mediana_edad = df_bank['age'].median()
df_bank['age'] = df_bank['age'].fillna(mediana_edad).astype(int)

# 3. Rellenar columnas de texto faltantes con 'unknown'
columnas_texto = ['job', 'marital', 'education', 'default']
for col in columnas_texto:
    df_bank[col] = df_bank[col].fillna('unknown')

# 4. Convertir 'euribor3m' a número de forma segura
if df_bank['euribor3m'].dtype == 'object':
    df_bank['euribor3m'] = df_bank['euribor3m'].str.replace(',', '.', regex=False)
df_bank['euribor3m'] = pd.to_numeric(df_bank['euribor3m'], errors='coerce')
df_bank['euribor3m'] = df_bank['euribor3m'].fillna(df_bank['euribor3m'].median())

# 5. LIMPIEZA EXTREMA de 'cons.price.idx' (para evitar que se vuelva 0)
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].astype(str).str.strip()
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].str.replace(',', '.', regex=False)
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].str.replace(r'[^\d.]', '', regex=True)
df_bank['cons.price.idx'] = pd.to_numeric(df_bank['cons.price.idx'], errors='coerce')
df_bank['cons.price.idx'] = df_bank['cons.price.idx'].fillna(df_bank['cons.price.idx'].median())

# 6. Convertir la columna 'date' a formato fecha de forma segura
df_bank['date'] = pd.to_datetime(df_bank['date'], errors='coerce', dayfirst=True)
if not df_bank['date'].dropna().empty:
    df_bank['date'] = df_bank['date'].fillna(df_bank['date'].dropna().mode()[0])

# 7. Eliminar la columna duplicada de índice si existe
if 'Unnamed: 0' in df_bank.columns:
    df_bank = df_bank.drop(columns=['Unnamed: 0'])

C:\Users\laura\AppData\Local\Temp\ipykernel_956\13795716.py:27: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_bank['date'] = pd.to_datetime(df_bank['date'], errors='coerce', dayfirst=True)

In [32]:
df_bank.info()

<class 'pandas.DataFrame'>
Index: 41974 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41974 non-null  int64
 1   job             41974 non-null  str
 2   marital         41974 non-null  str
 3   education       41974 non-null  str
 4   default         41974 non-null  object
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         41974 non-null  str
 8   duration        41974 non-null  int64
 9   campaign        41974 non-null  int64
 10  pdays           41974 non-null  int64
 11  previous        41974 non-null  int64
 12  poutcome        41974 non-null  str
 13  emp.var.rate    41974 non-null  float64
 14  cons.price.idx  41974 non-null  float64
 15  cons.conf.idx   41974 non-null  str
 16  euribor3m       41974 non-null  float64
 17  nr.employed     41974 non-null  str
 18  y               41974 non-null  str
 19  date            0 non-null      datetime64[s]
 20  latitude        41974 non-null  float64
 21  longitude       41974 non-null  float64
 22  id_             41974 non-null  str
dtypes: datetime64[s](1), float64(7), int64(5), object(1), str(9)
memory usage: 7.7+ MB

In [33]:
# voy a volver a corregir la columna 'date'
df_bank = pd.read_csv(ruta_bank, sep=',', header = 'infer', index_col = None)

df_bank['date'] = pd.to_datetime(df_bank['date'], errors='coerce', format='mixed')

if not df_bank['date'].dropna().empty:
    fecha_moda = df_bank['date'].mode().values[0]
    df_bank['date'] = df_bank['date'].fillna(fecha_moda)

In [34]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            0 non-null      datetime64[s]
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: datetime64[s](1), float64(7), int64(5), str(11)
memory usage: 7.9 MB

In [35]:
# 1. Volvemos a leer la columna 'date' original como texto puro (sin conversiones automáticas)
df_original = pd.read_csv(ruta_bank, sep=',', header = 'infer', index_col = None, usecols=['date'])

# 2. Forzamos la conversión usando el parámetro format='mixed' para que procese cualquier variante
df_bank['date'] = pd.to_datetime(df_original['date'], errors='coerce', format='mixed')

# 3. Si quedan nulos, calculamos la fecha más frecuente (la moda) limpiando los nulos temporales primero
if not df_bank['date'].dropna().empty:
    fecha_moda = df_bank['date'].dropna().mode().values[0]
    df_bank['date'] = df_bank['date'].fillna(fecha_moda)
else:
    df_bank['date'] = df_bank['date'].fillna(pd.Timestamp('2026-06-18'))

In [36]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            43000 non-null  datetime64[s]
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: datetime64[s](1), float64(7), int64(5), str(11)
memory usage: 7.9 MB

In [37]:
df_original = pd.read_csv(ruta_bank, sep=',', header = 'infer', index_col = None, usecols=['date'])

print(df_original[['date']].head(5))

                 date
0       2-agosto-2019
1  14-septiembre-2016
2     15-febrero-2019
3   29-noviembre-2015
4       29-enero-2017

In [38]:
ruta_bank =r"C:\Users\laura\OneDrive\Escritorio\bank-additional.csv"

In [39]:
import pandas as pd
import numpy as np

# 1. CARGA DEL ARCHIVO COMPLETO
df_bank = pd.read_csv(ruta_bank, sep=',', header='infer', index_col=None)

# 2. LIMPIEZA DE EDAD, CATEGORÍAS Y ÍNDICES
df_bank = df_bank.dropna(subset=['housing', 'loan'])

mediana_edad = df_bank['age'].median()
df_bank['age'] = df_bank['age'].fillna(mediana_edad).astype(int)

columnas_texto = ['job', 'marital', 'education', 'default']
for col in columnas_texto:
    df_bank[col] = df_bank[col].fillna('unknown')

if 'Unnamed: 0' in df_bank.columns:
    df_bank = df_bank.drop(columns=['Unnamed: 0'])

# 3. LIMPIEZA DE COLUMNAS NUMÉRICAS CON ENTRADAS EXTRAÑAS
for col in ['cons.price.idx', 'euribor3m']:
    if df_bank[col].dtype == 'object':
        df_bank[col] = df_bank[col].str.replace(',', '.', regex=False)
    df_bank[col] = pd.to_numeric(df_bank[col], errors='coerce')
    df_bank[col] = df_bank[col].fillna(df_bank[col].median())

# 4. CORRECCIÓN DE LA FECHA (Cambiando el dataframe in-place de forma segura)
df_bank['date'] = pd.to_datetime(df_bank['date'], errors='coerce', format='mixed')

if not df_bank['date'].dropna().empty:
    fecha_moda = df_bank['date'].dropna().mode().values[0]
    df_bank['date'] = df_bank['date'].fillna(fecha_moda)
else:
    df_bank['date'] = df_bank['date'].fillna(pd.Timestamp('2026-06-18'))

# 5. COMPROBACIÓN FINAL
df_bank.info()

<class 'pandas.DataFrame'>
Index: 41974 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41974 non-null  int64
 1   job             41974 non-null  str
 2   marital         41974 non-null  str
 3   education       41974 non-null  str
 4   default         41974 non-null  object
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         41974 non-null  str
 8   duration        41974 non-null  int64
 9   campaign        41974 non-null  int64
 10  pdays           41974 non-null  int64
 11  previous        41974 non-null  int64
 12  poutcome        41974 non-null  str
 13  emp.var.rate    41974 non-null  float64
 14  cons.price.idx  0 non-null      float64
 15  cons.conf.idx   41974 non-null  str
 16  euribor3m       41974 non-null  float64
 17  nr.employed     41974 non-null  str
 18  y               41974 non-null  str
 19  date            41974 non-null  datetime64[s]
 20  latitude        41974 non-null  float64
 21  longitude       41974 non-null  float64
 22  id_             41974 non-null  str
dtypes: datetime64[s](1), float64(7), int64(5), object(1), str(9)
memory usage: 7.7+ MB

In [40]:
# 1. Traemos la columna original en bruto sin alterar tu df_bank actual
df_aux = pd.read_csv(ruta_bank, sep=',', header='infer', usecols=['cons.price.idx'])

# 2. Forzamos a que sea texto para limpiar cualquier impureza
df_aux['cons.price.idx'] = df_aux['cons.price.idx'].astype(str).str.strip()

# 3. Reemplazamos comas por puntos por si acaso
df_aux['cons.price.idx'] = df_aux['cons.price.idx'].str.replace(',', '.', regex=False)

# 4. Convertimos a número (los errores que no entienda los dejará como nulos temporalmente)
df_aux['cons.price.idx'] = pd.to_numeric(df_aux['cons.price.idx'], errors='coerce')

# 5. Si generó nulos, calculamos la mediana real de los valores que SÍ se convirtieron bien
mediana_real = df_aux['cons.price.idx'].dropna().median()
df_aux['cons.price.idx'] = df_aux['cons.price.idx'].fillna(mediana_real)

# 6. Alineamos los datos rescatados con tu dataframe limpio actual (respetando las filas eliminadas)
df_bank['cons.price.idx'] = df_aux['cons.price.idx'].loc[df_bank.index]

# 7. ¡Comprobamos el resultado!
df_bank.info()

<class 'pandas.DataFrame'>
Index: 41974 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41974 non-null  int64
 1   job             41974 non-null  str
 2   marital         41974 non-null  str
 3   education       41974 non-null  str
 4   default         41974 non-null  object
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         41974 non-null  str
 8   duration        41974 non-null  int64
 9   campaign        41974 non-null  int64
 10  pdays           41974 non-null  int64
 11  previous        41974 non-null  int64
 12  poutcome        41974 non-null  str
 13  emp.var.rate    41974 non-null  float64
 14  cons.price.idx  41974 non-null  float64
 15  cons.conf.idx   41974 non-null  str
 16  euribor3m       41974 non-null  float64
 17  nr.employed     41974 non-null  str
 18  y               41974 non-null  str
 19  date            41974 non-null  datetime64[s]
 20  latitude        41974 non-null  float64
 21  longitude       41974 non-null  float64
 22  id_             41974 non-null  str
dtypes: datetime64[s](1), float64(7), int64(5), object(1), str(9)
memory usage: 7.7+ MB