In [3]:
import pandas as pd
import numpy as np

In [9]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
ruta_customer = r"C:\Users\laura\OneDrive\Escritorio\customer-details.xlsx"
df_customer = pd.read_excel(ruta_customer, sheet_name=0, header=0, index_col=None)

In [5]:
df_customer.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [6]:
df_customer.shape

(20115, 7)

In [7]:
todas_las_hojas = pd.read_excel(ruta_customer, sheet_name=None)

In [8]:
df_customer = pd.concat(todas_las_hojas.values(), ignore_index=True)

In [9]:
print("Total de filas leidas:", df_customer.shape[0])

Total de filas leidas: 43170

In [10]:
df_customer.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [11]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[us]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 2.3 MB

In [11]:
import pandas as pd

if 'Unnamed: 0' in df_customer.columns:
    df_customer = df_customer.drop(columns=['Unnamed: 0'])

df_customer['Dt_Customer'] = pd.to_datetime(df_customer['Dt_Customer'], errors='coerce')

df_customer = df_customer.drop_duplicates(subset=['ID'])

df_customer['Total_Dependents'] = df_customer['Kidhome'] + df_customer['Teenhome']

df_customer['Has_Kids'] = (df_customer['Total_Dependents'] > 0).astype(int)

df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Income             43170 non-null  int64
 1   Kidhome            43170 non-null  int64
 2   Teenhome           43170 non-null  int64
 3   Dt_Customer        43170 non-null  datetime64[us]
 4   NumWebVisitsMonth  43170 non-null  int64
 5   ID                 43170 non-null  str
 6   Total_Dependents   43170 non-null  int64
 7   Has_Kids           43170 non-null  int64
dtypes: datetime64[us](1), int64(6), str(1)
memory usage: 2.6 MB

In [12]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[us]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 2.3 MB

In [15]:
import pandas as pd

df_bank = pd.read_csv(r"C:\Users\laura\OneDrive\Escritorio\bank-additional.csv") 

df_merged = pd.merge(
    df_bank, 
    df_customer, 
    left_on='id_', 
    right_on='ID', 
    how='inner'
)

if 'ID' in df_merged.columns:
    df_merged = df_merged.drop(columns=['ID'])

df_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0_x       43000 non-null  int64
 1   age                37880 non-null  float64
 2   job                42655 non-null  str
 3   marital            42915 non-null  str
 4   education          41193 non-null  str
 5   default            34019 non-null  float64
 6   housing            41974 non-null  float64
 7   loan               41974 non-null  float64
 8   contact            43000 non-null  str
 9   duration           43000 non-null  int64
 10  campaign           43000 non-null  int64
 11  pdays              43000 non-null  int64
 12  previous           43000 non-null  int64
 13  poutcome           43000 non-null  str
 14  emp.var.rate       43000 non-null  float64
 15  cons.price.idx     42529 non-null  str
 16  cons.conf.idx      43000 non-null  str
 17  euribor3m          33744 non-null  str
 18  nr.employed        43000 non-null  str
 19  y                  43000 non-null  str
 20  date               42752 non-null  str
 21  latitude           43000 non-null  float64
 22  longitude          43000 non-null  float64
 23  id_                43000 non-null  str
 24  Unnamed: 0_y       43000 non-null  int64
 25  Income             43000 non-null  int64
 26  Kidhome            43000 non-null  int64
 27  Teenhome           43000 non-null  int64
 28  Dt_Customer        43000 non-null  datetime64[us]
 29  NumWebVisitsMonth  43000 non-null  int64
dtypes: datetime64[us](1), float64(7), int64(10), str(12)
memory usage: 9.8 MB